#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Empty downloads folder
function empty-downloads() {
    mv $HOME/Downloads/* $HOME/.Trash
}

# Make directory then cd into it
function mkd() {
    mkdir -p "$@" && cd "$_"
}

# --- clear ---
alias c='clear'

# --- killall typos ---
alias kilall='killall'

# --- lock/unlock file ---
alias lock='chflags uchg'
alias unlock='chflags nouchg'

# --- ls ---
alias l='ls -cf' # default
alias ls='ls -cf' # default
alias la='ls -af' # show hidden files
alias ll='ls -alf' # show hidden files, long format

# --- xcode ---
alias xcode='open *.xcworkspace || open *.xcodeproj' # open xcode project in current directory

# --- homebrew  packages ---
alias gs='git status' # git
alias g='googler --colors acegxy --count 8' # googler
eval $(hub alias -s) # hub
eval $(thefuck --alias please) # thefuck
eval $(thefuck --alias fuck) # thefuck
alias empty-trash='trash -e' # trash
alias trash-empty='trash -e' # trash


# --- zsh built-in autocompletion ---
if [[ "${terminfo[kcbt]}" != "" ]]; then
    bindkey "${terminfo[kcbt]}" menu-complete # [shift-tab]
fi

# --- zsh plugins ---
alias q='quick-look' # osx
alias ql='quick-look' # osx
bindkey "^i" autosuggest-accept # zsh-autosuggestions [tab]

# --- custom zsh plugins ---
alias fod='fuzzy-open-directory'
alias fof='fuzzy-open-file'
alias gui='google-browser'
alias o='open-app-or-website'


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
